version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
      target: ${ENVIRONMENT:-production-pseudo}
      args:
        NODE_HOST: ${NODE_HOST:-node}
    ports:
      - ${NGINX_PORT:-8080}:80
    volumes:
      - .:/usr/local/app/hello-cors

  php-fpm:
    build: api
    volumes:
      - ./api:/usr/local/app/hello-cors/api

  node:
    build:
      context: front
      target: ${ENVIRONMENT:-production-pseudo}
    # ports:
    #   - ${NODE_PORT:-8888}:8888
    volumes:
      - ./front:/usr/local/app/hello-cors/front