version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - ${NGINX_PORT:-8080}:80
    volumes:
      - .:/usr/local/app/hello-cors

  php-fpm:
    build: api
    volumes:
      - ./api:/usr/local/app/hello-cors/api

  node:
    build: front
    ports:
      - ${NODE_PORT:-8888}:8888
    volumes:
      - ./front:/usr/local/app/hello-cors/front